### ISSUE TITLE
Not working on Microsoft Edge.

### ISSUE THREAD

**Issue by Codeingit14** [wseagar/eight-dollars#40] opened 2022-11-12 04:14 UTC
When I unpacked the file and use it on Microsoft Edge, the extension doesn't work

**Comment by LukeSaward1** [comment] 2022-11-12 08:57
Read the README. Instructions for Edge are coming soon.

**Comment by infinitepower18** [comment] 2022-11-12 13:57
It's working for me

<img width="1684" alt="image" src="https://user-images.githubusercontent.com/44692189/201477435-6d28f862-a299-49ad-a128-6294f44fbf63.png">

**Comment by infinitepower18** [comment] 2022-11-12 14:20
@LukeSaward1 I've added instructions for Edge in #43

**Comment by infinitepower18** [comment] 2022-11-12 14:27
Just found out it's on the Chrome Web Store now, but it's an older version: https://chrome.google.com/webstore/detail/eight-dollars/fjbponfbognnefnmbffcfllkibbbobki

Installs and works fine in Edge.

**Comment by wseagar** [comment] 2022-11-13 21:30
Edge should work if you use the chrome web store release. Any delays between versions on github and on chrome web store is because of the time the chrome web store takes to verify a release.

**Comment by 3kh0** [comment] 2022-11-14 12:18
@wseagar could we close this issue?

**Comment by wseagar** [comment] 2022-11-14 20:00
Yep Edge has been confirmed working via many sources.

**Closed** 2022-11-14 20:00 UTC
