### ISSUE TITLE
Userscript version?

### ISSUE THREAD

**Issue by krisu5** [wseagar/eight-dollars#45] opened 2022-11-12 15:52 UTC
I know extensions are more popular and mainstream option, but personally I prefer userscripts for site related tweaks.

[Tampermonkey](https://www.tampermonkey.net/) is most popular userscript manager, but I use [Violentmonkey](https://violentmonkey.github.io/).

I'm personally fine without settings, if that's issue.

**Comment by daniel-white** [comment] 2022-11-12 17:23
duplicate of #19

**Closed** 2022-11-12 17:47 UTC
