### ISSUE TITLE
Label is only showing on profile and not individual tweets?

### ISSUE THREAD

**Issue by menma1234** [wseagar/eight-dollars#23] opened 2022-11-11 03:16 UTC
Running Firefox 106.0.5.

Not quite sure why this is happening, but:

![image](https://user-images.githubusercontent.com/9199262/201255259-79abb7d2-cf4c-4f7b-85bf-e2fdaabba227.png)

And for some reason, when I click into a tweet and go back, then the pinned tweet shows the label:

![image](https://user-images.githubusercontent.com/9199262/201255304-2079bc87-8eff-4e3e-afb2-bb7c86ba48bd.png)

**Comment by wseagar** [comment] 2022-11-11 04:33
Have had a few reports of this sort of behavior. I haven't been able to reproduce it yet. Can you try closing all of your Firefox tabs and starting fresh on that page?

Keen to hear if anyone here in the open source community knows why it's happening or if I've done something fundamentally wrong in the extension. Twitter isn't really an easy site to mod with an extension (lot's of dynamic content w React, themes which change things, no clear selectors or css id's on elements).

**Comment by GeorgeSpelvin** [comment] 2022-11-11 06:00
I'm seeing the same but, on my end, the badge does -not- follow when I go back to the tweet.  I'm seeing the badge -only- on th profiles.

**Comment by wseagar** [comment] 2022-11-11 09:52
Believe I've tracked down this flakiness. Was caused by some stupid code I did when I hacked this together last night. Will be fixed when we get v1.2 out tomorrow (hopefully with the options panel).

Fix is here https://github.com/wseagar/eight-dollars/commit/a1d053706e70e7c62b06ffca040d52a6499d23ba

Thanks for reporting @menma1234 and @GeorgeSpelvin . If it's still not working after v1.2 please feel free to reopen this.

**Closed by wseagar** 2022-11-11 09:52 UTC

**Comment by menma1234** [comment] 2022-11-12 23:02
@wseagar I updated to 1.2 and restarted Firefox even but I'm still getting the same results:

![image](https://user-images.githubusercontent.com/9199262/201497872-b7e3ffe5-b54d-4fe8-9a8c-5e5555465810.png)

**Comment by noway** [comment] 2022-11-12 23:50
@menma1234 try the latest in `main` branch

**Comment by menma1234** [comment] 2022-11-13 01:06
@noway Is there an easy way to package it for Firefox? There's unfortunately no instructions for that.

**Comment by GeorgeSpelvin** [comment] 2022-11-13 17:58
Found the main file (I'm not savvy to github) and that is working mostly fine now on Chrome.  👍🏻
Only thing not working atm is the comic sans which isn't a big thing.  It *does* work on the font but not the text when Enable Text is turned off.  _(Earlier when text was enabled, it wasn't converting the $ to Comic Sans but, while typing this out, it started to do so.  Weird)._
![image](https://user-images.githubusercontent.com/43255485/201536764-3352055f-6580-45f6-b888-c2322b8df12e.png)
![image](https://user-images.githubusercontent.com/43255485/201536817-a7e7397a-51aa-4e68-a0b0-1906ea6207de.png)

**Comment by menma1234** [comment] 2022-11-14 02:23
Looks fixed now on v1.3, thanks!
